# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 965dcfb8c5fe550612aebb3582ba6c7e81acc0d2158d6649c05378fd01bd66947cb81ead71ca9518a3c9817a1e7d557dd9a7ba82077079eb484dc0c6b6fde3d0

test:
  secret_key_base: d6e1c68f23666f162cd2ed0e2e9cc159a32377f7766fd91e36c02166bc615cea699f7fe2989577eb031630cba2dff760f59b2f2e19e4347b9216673446034534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
